name: Setup badges

on:
  schedule:
   - cron: "5 * * * *"
  workflow_dispatch:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
     - run: |
        sudo gem install badgerbadgerbadger
        badger badge
